import { Arizonia, Bodoni_Moda, Raleway, Ropa_Sans } from "next/font/google";
import "./globals.css";
// import Header from "./components/header/Header";
// import StickyCategories from "./components/stickyCategories/StickyCategories";
// import { CategoryProvider } from "./context/CategoryContext";
import HeaderWrapper from "./components/header/HeaderWrapper";
import { CartProvider } from "./context/CartContext";
// import Cart from "./components/cart/Cart";
import Footer from "./components/footer/Footer";
import { PopupProvider } from "./context/PopContext";

// const kaisei = Kaisei_Tokumin({
//   variable: "--font-kaisei",
//   weight: ["400", "500", "700"],
//   subsets: ["latin"],
// });

const arizonia = Arizonia({
  variable: "--font-arizonia",
  weight: ["400"],
  subsets: ["latin"],
});

const bodoni = Bodoni_Moda({
  variable: "--font-bodoni",
  weight: ["400"],
  subsets: ["latin"],
});

const ropa = Ropa_Sans({
  variable: "--font-ropa",
  subsets: ["latin"],
  weight: ["400"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Kaisei+Tokumin:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${ropa.variable} ${raleway.variable} ${bodoni.variable} ${arizonia.variable} `}
      >
        <CartProvider>
          <HeaderWrapper />
          <main className="relative">
            <PopupProvider>{children}</PopupProvider>
          </main>
          {/* <Cart /> */}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
