import { Arizonia, Kaisei_Tokumin, Raleway, Ropa_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import StickyCategories from "./components/stickyCategories/StickyCategories";
import { CategoryProvider } from "./context/CategoryContext";
import HeaderWrapper from "./components/header/HeaderWrapper";
import { CartProvider } from "./context/CartContext";
import Cart from "./components/cart/Cart";

const kaisei = Kaisei_Tokumin({
  variable: "--font-kaisei",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

const arizonia = Arizonia({
  variable: "--font-arizonia",
  weight: ["400"],
});

const ropa = Ropa_Sans({
  variable: "--font-ropa",
  subsets: ["latin"],
  weight: ["400"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${ropa.variable} ${raleway.variable} ${arizonia.variable} ${kaisei.variable}`}
      >
        <CartProvider>
          <HeaderWrapper />
          {children}
          <Cart />
        </CartProvider>
      </body>
    </html>
  );
}
